2024-11-09 15:03:07-root-ERROR-Test9:Traceback (most recent call last):
  File "D:\pycharmwenjian\Python Basic Syntax\Chapter Four\Test9.py", line 21, in <module>
    print(1/0)
ZeroDivisionError: division by zero

